### ISSUE TITLE
Receiving 400 validation_error when running in GitHub Actions

### ISSUE THREAD

**Issue by jimmyceroneii** [resend/resend-node#522]
## Reproduction Steps: 

So far I've been able to reproduce this in GitHub Actions for every version from 3.5 up to 4.5.1. I am not able to reproduce the error locally for reasons that are still not clear to me. Further complicating things, this error is not occurring in my Rust based repository that is using Resend via GitHub Actions. 

Runner Type: ubuntu-latest

Functions Impacted: 

- I've been able to replicate this in GitHub Actions with the `get`, `send`, and `fetchRequest` functions on `Resend`. 

## Behavior

For GitHub Actions only when using the node SDK, I'm seeing the following error: 

```json
{"statusCode":400,"message":"API key is invalid","name":"validation_error"}
```

I find this to be problematic for several reasons: 

- The same API key works just fine locally and in another GitHub Action using Rust
- The 400 `statusCode` technically corresponds to the `invalid_idempotency_key` error, not the `validation_error` or the "API key is invalid error"
- I am not setting the `idempotencyKey` at all, anywhere. 

## Example Code

Here is the code I am using, which is working locally but not in GitHub Actions: 

```ts
import * as dotenv from "dotenv";
import { Resend } from "resend";
dotenv.config();

const resend = new Resend(process.env.RESEND_API_KEY);

export const sendEmail = async (emailBody: string) => {
  const emailResponse = await resend.emails.send({
    from: "onboarding@resend.dev",
    to: "jimmy.cerone@gmail.com",
    subject: "Weekly Newsletter Template",
    html: emailBody,
  });

  if (emailResponse.error) {
    throw new Error(JSON.stringify(emailResponse.error));
  }
};
```

I did not change the code above, but I saw failures start happening on 05/07/2025. 

## Theory

There do not appear to be any suspicious commits in the `resend-node` repository around this time. I've reviewed the `idempotencyKey` related code and all looks well there. I would say this appears to be server side related, but I checked my Resend logs and these requests are not even hitting the server. At this point, I have no clue what is going wrong here. Any help is appreciated.

**Comment by emiliosheinz** [comment]
Hi @jimmyceroneii, what do you mean by "when running in GitHub Actions"? Does it mean the server errors out only when it is built and deployed through GitHub Actions, or are you trying to send emails from within the GitHub Actions environment?

Additionally, have you already made sure that `process? env.RESEND_API_KEY` has the correct value when you instantiate a new Resend instance? It could be that your GitHub Actions are not correctly setting the environment variables, which is making the API calls error out.

**Comment by jimmyceroneii** [comment]
Hey @emiliosheinz! I am using Resend in the context of a cron based GitHub Action. You can see the yaml below: 

```
name: Daily Round Up 

on:
  schedule:
    - cron: '0 11 * * *' # Runs the job every day at 6 am EST
  workflow_dispatch: # allow for manual trigger

jobs:
  send-daily-round-up:
    runs-on: ubuntu-latest
    environment:
      name: Production

    env:
      EXA_API_KEY: ${{ secrets.EXA_API_KEY }}
      RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
      READWISE_API_TOKEN: ${{ secrets.READWISE_API_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: yarn

      - name: Run script
        run: bun backend/experiments/daily-roundup/index.ts
```

Given the above, I am sending the email directly from GitHub Actions, rather than deployed a built asset elsewhere. In this case, I'm using GitHub Actions in a similar way to a Lambda which is triggered by a `cron`. 

I have made sure that the API Key is being passed along correctly in the GitHub Action.
